name: Cybersecurity Chatbot Test Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    # ----------------------------------
    # 1. Checkout code
    # ----------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # ----------------------------------
    # 2. Setup .NET
    # ----------------------------------
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # ----------------------------------
    # 3. Run tests (automatically restores and builds)
    # ----------------------------------
    - name: Run tests
      run: dotnet test --no-restore
